# Output helpers: stamp/profile dirs, the run index and backup-to-latest info.
import json
from datetime import datetime, timezone
from pathlib import Path

from exportlib import TOOL_VERSION
from exportlib.config import default_bkp_dir
from exportlib.util import safe_filename, selection_label


def make_outdir_final(base, profile: str, stamp: str | None = None):
    stamp = stamp or datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M")
    target = base / stamp / profile
    n = 2
    while target.exists():
        target = base / f"{stamp}@{n}" / profile
        n += 1
    target.mkdir(parents=True, exist_ok=False)
    return target


def write_index(index_path, out_dir, args, db_path, sessions, written, total_msgs, total_comp):
    with index_path.open("w", encoding="utf-8") as f:
        f.write("# opencode session export\n\n")
        f.write("| Field | Value |\n|---|---|\n")
        f.write(f"| Product | `{args.profile}` |\n")
        f.write(f"| Date | {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')} |\n")
        f.write(f"| Source DB | `{db_path}` |\n")
        # One row for the effective selection, whatever rule produced it
        # (filter / ids / last N / since DATE / all) — the same phrase as
        # metadata.json's `selection` and the "matched nothing" error.
        f.write(f"| Selection | {selection_label(args)} |\n")
        f.write(f"| Sessions (roots/subagents/total) | {len(written)} / {sum(len(s[1]) for s in written)} / {len(sessions)} |\n")
        # Subagent inclusion: only surfaced when a flag narrowed the set (the
        # default run keeps the historical rows untouched).
        if getattr(args, "no_subagents", False):
            f.write("| Subagents | `excluded (--no-subagents)` |\n")
        elif getattr(args, "no_orphan_subagents", False):
            f.write("| Subagents | `only those whose parent is exported (--no-orphan-subagents)` |\n")
        f.write(f"| Messages | {total_msgs} |\n")
        f.write(f"| Compactions | {total_comp} |\n")
        f.write(f"| Tool output | `{args.tool_output}` |\n")
        f.write(f"| Reasoning | `{'on' if not args.no_reasoning else 'off'}` |\n")
        f.write(f"| JSON archive | `{'on' if args.json else 'off'}` |\n")
        f.write(f"| Sanitize | `{'on' if args.sanitize else 'off'}` |\n")
        f.write("| Extraction | Python `exportlib` (read `mode=ro`) from `~/.local/share/opencode/opencode.db` |\n")
        f.write(f"| Full metadata | [`metadata.json`](metadata.json) |\n\n")
        f.write("## Sessions\n\n")
        for i, (root, subs, rfolder) in enumerate(written, 1):
            rt = root["title"] or root["slug"]
            root_md = rfolder / f"{safe_filename(rt)}.md"
            rel_d = root_md.relative_to(out_dir)
            f.write(f"{i}. **[{rt}]({rel_d})**  — `{root['id']}`  · agent `{root.get('agent') or '?'}`\n")
            if subs:
                f.write("   \n   Subagents:\n")
                for sid_ in subs:
                    sub = sessions[sid_]
                    st = sub["title"] or sub["slug"]
                    rel_s = (rfolder / "subagents" / f"{safe_filename(st)}_{sub['id'][:8]}.md").relative_to(out_dir)
                    f.write(f"   - [{st}]({rel_s})  `{sub['id'][:8]}`\n")
            f.write("\n")
        f.write("---\n")
        f.write(f"\nGenerated by `opencode-db` v{TOOL_VERSION}.\n")


def last_backup_info():
    manifest = Path(default_bkp_dir()) / "manifest.json"
    if not manifest.exists():
        return None
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
        b = data.get("backups") or []
        if not b:
            return None
        b = sorted(b, key=lambda x: x.get("date", ""))
        last = b[-1]
        return {"file": last.get("file"), "date": last.get("date")}
    except Exception:
        return None